[tool.ruff]
line-length=122
select = ["F", "E", "W", "B"]
ignore = ["E203"]

[tool.isort]
profile = "black"
known_third_party = ["django", "requests"]

[tool.pytest.ini_options]
django_settings_module = "auth_service.settings"
addopts = "--nomigrations"
python_files = ["tests/*.py"]
